# Generated by Django 4.2.1 on 2023-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
