# Generated by Django 4.2.1 on 2023-06-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('code', 'Code'), ('document', 'Document'), ('admin', 'Admin')], max_length=20),
        ),
    ]
